var GAME_LEVELS = [
  ["        x                              xxxxx                                x  ",
   "    xxxx x                             x!!!x                                x  ",
   "  xxx  x  x                            xxvxx                                 x  ",
   "  x     x                                                                    x  ",
   "  x   xx                                                           oo   y    x  ",
   "  x                                                o                y        x  ",
   "  x                                          w             o     y   o       x  ",
   "  x                     o                     o    xx      xx    x!!!x       x  ",
   "  x                                 oyo      xx                  x!!!x       x  ",
   "  x                                                              xx!xx   x   x  ",
   "  x                                xxxxx                          xvx        x  ",
   "  x                          x     x                 y                       x  ",
   "  x           o    m     y    x!!!!!x     o o                                x  ",
   "  x            y        o     x!!!xx                 o                xx     x  ",
   "  x                    xxx     xxx       xxxxx                             o x  ",
   "  x          xxxx       o                            x       y    y      y   x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxx           xxxxxxx   xxxxxxxxx  ",
   "                              x   x            x           x                    ",
   "                              x o x            x!!!!!!!!!!!x                    ",
   "                              x x x            x!!!!!!!!!!!x                    ",
   "                              x   x            xxxxxxxxxxxxx                    ",
   "                              x!!!x                                             ",
   "                              xxxxx                                             "],
  ["                        x                                                          x                            x ",
   "                        x                                                          x                            x ",
   "                        x              o   |                                       x  o               o         x ",
   "                        x           |          o                                   x      |       w             x ",
   "                        x                                                          x  x       xx      x         x ",
   "                        x                         |                                xoox               x         x ",
   "                        x      xxxxxxxxxxxxxxxxxxxxxxx        |                    xoox!!!!!!!!!!!!!!!x         x ",
   "                        x                            x                       x     xxxxxxxxxxxxxxxxxxxxxxx      x ",
   "                        xo                 w         x                     | x     x                            x ",
   "                        xx                           x   xxxxxx              x     x                           xx ",
   "                        x                            x   x                  ox     x                            x ",
   "                        x     o     =  o             x   x                   x     x          o    w     |      x ",
   "                        x         w                  x   x              xxxxxx     x                            x ",
   "                        xxxxxxxxxxxxxxxxxxxxxxxx     x   x  |                      x          x       xx      x x ",
   "         x           x           x!x           x     x   xo                        x          x               x x ",
   "         w           w            v            xx    x   x                         x          x!!!!!!!!!!!!!!!x x ",
   "                                               x     x   xxxxxx    m               x       xxxxxxxxxxxxxxxxxxxxxx ",
   "                                               x    ox                             x                            x ",
   "                          o                    x     x         !!!!!!!!            x                            x ",
   "                                               x    xx   xxxxxxxxxxxxxx            xx                           x ",
   "     @                   xxx                   x     x   x                         x       w      w             x ",
   "    xxx        o         x x                   x     x   x                         x  o               o         x ",
   "    x x                  x x                   x     x   x                xxx      x                            x ",
   "    x x                  x!x           !!!!!!!!xx    x!!!x     =                  xx  x       xx      x         x ",
   "    x x      xxxxxx      x!x xxx      xxxxxxxxxx     x!!!x                         x  x               x         x ",
   "    x x      x    x  x   x!x xx   o              o  xx!!!x o      xxx              x  x!!!!!!!!!!!!!!!x      o  x ",
   "    x x      x    x      x!x xx          o          xx!!!x                     xxxxxxxxxxxxxxxxxxxxxxxxxx       x ",
   "    x x      x    x      x!x!xxx      xxxxxxxxxxxxxx!!!!!x                                                      x ",
   "    x x      x    x      x!x!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xxxxx          x        o      o                       x ",
   "!!!!x x!!!!!!x    x!!!!!!x!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                       x            x                                         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                                                                           o      o    o      ",
   "                                                       |            |                   o                     ",
   "                                                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                               o        xxxxx     yyyyyyyyy                   ",
   "                                                     o            xxxxxx         y    x    y                  ",
   "                                        |                   xxxxxx              y    x!x    y                 ",
   "                                                  xxxxxxxxxx                   y    x!!!x    y                ",
   "                                    o         xxxx                            y    x!!!!!x    y               ",
   "                                xxxxxxxxxxxxxxx                               y    x!!!!!x    y               ",
   "                             xxx                                               y    x!!!x    y                ",
   "                          xxx                                                   y    x!x    y                 ",
   "                        xx                                                       y    x    y                  ",
   "                   xxxxx                                                          yyyyyyyyy                   ",
   "                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              ",
   "  x                                                                                            x              ",
   "  x                           o   o                                 o                o          xx   xxxxxxx  ",
   "  x       xxxxxxx                       x                x                   xx                   x x      x  ",
   "  x       x     xmmmmmmmmmmmmmmmmmmmmmmmxmmmmmmmmmmmmmmmmmxmmmmmmmmmmmmmmmmmxm mmmmmmmmx n        x x      x  ",
   "  x       x     xxxxxxxx   xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx         x x      x  ",
   "  x       x             !!!                   !!!                      !!!               xx       x x      x  ",
   "  x       xxxx     xxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxx       x   x     x  ",
   "  x           x   x             x   x                     x   x                          x        x!x      x  ",
   "  x            x x               x x                       x x                           x         v       x  ",
   "  x             !                 !                         !                            xx                x  ",
   "  x             v                 v                         v                            x           w     x  ",
   "  x                                                                                      x                 x  ",
   "  x                                                                                      xxxxxxx           x  ",
   "  x                                            o                                         x                 x  ",
   "  x                                                                                                        x  ",
   "  x                   !                        !                         !                        w   xxxxxx  ",
   "  x             o    x x           o          x x              o        x x                                x  ",
   "  x      @          x   x                    x   x                     x   x                               x  ",
   "  xxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx         x  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "        x                                             x                                                    x  ",
   "        x                                             x   m         =                 m        =           x  ",
   "        x                                                                                                  x  ",
   "        x                                                      xxxx       xxxx       xxxx       xxxx       x  ",
   "        x                                                      x  x       x  x       x  x       x  x       x  ",
   "        x                                                      x  x       x  x       x  x       x  x  ooo  x  ",
   "        x                                                      x  x       x  x       x  x       x  x  ooo  x  ",
   "        x                              o               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "        x                          oooooo                                                                  x  ",
   "        x                              o                                                                   x  ",
   "        x                                      xx                                                          x  ",
   "        x                                                                                                  x  ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         !     o       !     o                   x  ",
   "                                         x              x         !x!           !x!                        x  ",
   "                                         x            o x  xx      !     xx      !     xx                  x  ",
   "                                         x   xx         x                                                  x  ",
   "                                         x           xxxx                                     xxx          x  ",
   "     o                                               x   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x        xxx  ",
   "        x                           o               xx xxx          xxx          xxx            x          x  ",
   "        x                 o        ooooo             xx   x        x   x        x   x           x o        x  ",
   "xxx  @  x                           o                x     x      x     x      x     x          x          x  ",
   "  x     x                                        xxxxx     xxxxxxxx     xxxxxxxx     xxxxxxxxxxxxxx        x  ",
   "  x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                 x  ",
   "  x     x    x!x         x!x         x!x x                                                                 x  ",
   "  x     xxxxxxvxxxxxxxxxxxvxxxxxxxxxxxvxxx                           |                                   xxx  ",
   "  x                             w                       |                                                  x  ",
   "  x                                              o             o                                           x  ",
   "  x                                                                                                        x  ",
   "  x                 w                           xxxxxx     xxxxxxxx     xxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx  ",
   "  x       o               o            o       x     x     x      x     x      x  |  x                        ",
   "  x                                           x       x   x        x   x        x o x!!!!!!!!!!!!!!!!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxxx   xxxxxxxxx   xxxxxxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                  x!!!x       x!!!x                                                                           "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
